# Generated by Django 5.0.7 on 2025-01-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_organiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subscriber', models.CharField(max_length=20, unique=True)),
                ('email_subscriber', models.EmailField(max_length=254)),
                ('date_subscribe', models.DateTimeField(auto_now_add=True)),
                ('number_of_tickets', models.PositiveIntegerField(default=1)),
                ('name_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='events.event')),
            ],
        ),
    ]
